name: 04 - Publish Todo-App

on:
  push:
    paths:
      - 'application/**'
      - 'cdk/**/*Service*'
      - 'cdk/pom.xml'
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    name: Build and deploy
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Build application
        working-directory: application
        run: ./gradlew build --stacktrace

      - name: Create Docker image tag
        id: dockerImageTag
        run: echo "tag=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Publish Docker image to ECR registry
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE_TAG: ${{ steps.dockerImageTag.outputs.tag }}
        working-directory: application
        run: |
          docker build -t todo-app .
          docker tag todo-app ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/todo-app:${DOCKER_IMAGE_TAG}
          docker tag todo-app ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/todo-app:latest
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/todo-app:${DOCKER_IMAGE_TAG}
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/todo-app:latest

      - name: Sending deployment event to queue
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE_TAG: ${{steps.dockerImageTag.outputs.tag}}
        run: |
          export EVENT_PAYLOAD="\
            {\"commitSha\": \"$GITHUB_SHA\",\
             \"ref\": \"main\", \
             \"owner\": \"stratospheric-dev\", \
             \"repo\": \"stratospheric\", \
             \"workflowId\": \"05-update-todo-app-in-staging.yml\", \
             \"dockerImageTag\": \"$DOCKER_IMAGE_TAG\"}"
          aws sqs send-message \
            --queue-url https://sqs.${AWS_REGION}.amazonaws.com/${AWS_ACCOUNT_ID}/todo-app-deploymentsQueue.fifo \
            --message-group-id default \
            --message-deduplication-id $GITHUB_SHA \
            --message-body "$EVENT_PAYLOAD"